// AUTO-GENERATED by scripts/generate-blurhashes.mjs. Do not edit by hand.
// Run `node scripts/generate-blurhashes.mjs` after adding or replacing
// images/videos under public/assets.

export type BlurhashEntry = { hash: string; w: number; h: number };

export const blurhashes: Record<string, BlurhashEntry> = {
  "/assets/backstory/photo-1.webp": {
    "hash": "TVF;pM,BbwGwNGX9TfS4WBAvWXrq",
    "w": 48,
    "h": 64
  },
  "/assets/backstory/photo-2.webp": {
    "hash": "TYGlY4xtM{~qogs;?JbIWA?bkBR*",
    "w": 48,
    "h": 64
  },
  "/assets/happier/moment-1.webp": {
    "hash": "TXGlY4xtM_~qogs;?KbIWA?bkBR*",
    "w": 48,
    "h": 64
  },
  "/assets/happier/moment-2.webp": {
    "hash": "UMH_0%015kMx4nRk%gt7~pIUs-M{R*M|-oM|",
    "w": 64,
    "h": 64
  },
  "/assets/happier/phone-left.webp": {
    "hash": "TCJH89tMR$PXIpk9Mkt1oeTdIpiw",
    "w": 30,
    "h": 64
  },
  "/assets/happier/phone-right.webp": {
    "hash": "TC9ZvC=vn#~C-TaxSgo#R.EgOFah",
    "w": 30,
    "h": 64
  },
  "/assets/happier/phone.webp": {
    "hash": "T56[5L?Zax~o-.jZ%Kxuj[kDkDn+",
    "w": 30,
    "h": 64
  },
  "/assets/hero/hero-1.webp": {
    "hash": "LtF%0,%MRiozlCSiV?t8%hkXRjWV",
    "w": 64,
    "h": 48
  },
  "/assets/hero/hero-10.webp": {
    "hash": "LXD]6o%2IURi~VxaM{RjR,n~ofR*",
    "w": 64,
    "h": 42
  },
  "/assets/hero/hero-11.webp": {
    "hash": "LmGlbZxvtRs;yZaeWBbFR*RjWAWB",
    "w": 64,
    "h": 42
  },
  "/assets/hero/hero-2.webp": {
    "hash": "TWIN~xi^kr.T-njcJ:tQM{?Gt7oI",
    "w": 48,
    "h": 64
  },
  "/assets/hero/hero-3.webp": {
    "hash": "LWE3VcIVNGtR%%j=ofW=NztQRjaK",
    "w": 64,
    "h": 42
  },
  "/assets/hero/hero-4.webp": {
    "hash": "TGFEu}t8-S8w$eI;D%kCt8?^bbr=",
    "w": 48,
    "h": 64
  },
  "/assets/hero/hero-5.webp": {
    "hash": "TRFO$1%hW?~WXTt7NGbHt8aJn#NH",
    "w": 48,
    "h": 64
  },
  "/assets/hero/hero-6.webp": {
    "hash": "TPHB-xi_WZ%M-:-:~qM{xuV[WB%L",
    "w": 48,
    "h": 64
  },
  "/assets/hero/hero-7.webp": {
    "hash": "TOK,NN?E~U_0xs%0^ixtxtt6oeWB",
    "w": 48,
    "h": 64
  },
  "/assets/hero/hero-8.webp": {
    "hash": "LVG@[9~BoyV@%1M{s:xZXSnis:R+",
    "w": 64,
    "h": 48
  },
  "/assets/hero/hero-9.webp": {
    "hash": "LBDv4a.A?HX3D}D$0M%1?GWZ-;M|",
    "w": 64,
    "h": 42
  },
  "/assets/og-careers.png": {
    "hash": "L39sxK0w^l+Y0LrC-m%N00}@NaI.",
    "w": 64,
    "h": 34
  },
  "/assets/press/press-1.webp": {
    "hash": "LY7-:zx8RgI]kcWAjXoII[NMoexV",
    "w": 64,
    "h": 39
  },
  "/assets/press/press-2.webp": {
    "hash": "L9B63bpI00bwAjQU*Joa0Rx@+@R6",
    "w": 64,
    "h": 34
  },
  "/assets/press/press-3.webp": {
    "hash": "LoOpY;xa-:t7s;j=bGjZ~pWBM{of",
    "w": 64,
    "h": 33
  },
  "/assets/press/press-4.webp": {
    "hash": "LpPERPoe}+xD-Qa}I@oJxVoJNeWY",
    "w": 64,
    "h": 36
  },
  "/assets/press/press-5.webp": {
    "hash": "LCJHmw0000ks00?b=|D*00xv~Ue,",
    "w": 64,
    "h": 36
  },
  "/assets/press/press-6.webp": {
    "hash": "LFC?.V-p00Io_4xaITNZS~o#r?RO",
    "w": 64,
    "h": 36
  },
  "/assets/tiktoks/tt-1.mp4": {
    "hash": "TDIW}=8{Bi;NDkJ*~pIpV@Eg9axa",
    "w": 36,
    "h": 64
  },
  "/assets/tiktoks/tt-2.mp4": {
    "hash": "TWF?IhxuR$_Nt7a%x]xZaexYtRRj",
    "w": 36,
    "h": 64
  },
  "/assets/tiktoks/tt-3.mp4": {
    "hash": "TOFhS9IoIo~BoJoz0f-UNH57WVV[",
    "w": 36,
    "h": 64
  },
  "/assets/tiktoks/tt-4.mp4": {
    "hash": "T6F#zG8|x]~nXmwa00_34:0K0L9G",
    "w": 36,
    "h": 64
  },
  "/assets/tiktoks/tt-5.mp4": {
    "hash": "TDF}=o~2?tptM^t44tv#MzIL-ot9",
    "w": 36,
    "h": 64
  },
  "/assets/whatitslike/photo-1.webp": {
    "hash": "LhJ8FY?bIot6~WxtWVxuNGR*e.aK",
    "w": 64,
    "h": 54
  },
  "/assets/whatitslike/photo-2.webp": {
    "hash": "TSGH;vt7RoNfa}WBWYRk%1~AxZM}",
    "w": 48,
    "h": 64
  }
};
